version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    links:
      - database
    volumes:
      - .:/home/app
  
  database:
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5000:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
